// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include "MainRuntime_inference.h"

#include <nnablart/functions.h>
#include <string.h>

typedef struct {
    void *buffer_pool[2];
    void *param_pool[24];
    rt_buffer_allocate_type_t variable_buffers_allocate_type[41];

    // Variables
    rt_variable_t v0; ///< Input
    int v0_shape[4];
    rt_variable_t v1; ///< Convolution/conv/W
    int v1_shape[4];
    rt_variable_t v2; ///< Convolution/conv/b
    int v2_shape[1];
    rt_variable_t v3; ///< Convolution_2/conv/W
    int v3_shape[4];
    rt_variable_t v4; ///< Convolution_2/conv/b
    int v4_shape[1];
    rt_variable_t v5; ///< BatchNormalization/bn/beta
    int v5_shape[4];
    rt_variable_t v6; ///< BatchNormalization/bn/gamma
    int v6_shape[4];
    rt_variable_t v7; ///< BatchNormalization/bn/mean
    int v7_shape[4];
    rt_variable_t v8; ///< BatchNormalization/bn/var
    int v8_shape[4];
    rt_variable_t v9; ///< Convolution_3/conv/W
    int v9_shape[4];
    rt_variable_t v10; ///< Convolution_3/conv/b
    int v10_shape[1];
    rt_variable_t v11; ///< BatchNormalization_2/bn/beta
    int v11_shape[4];
    rt_variable_t v12; ///< BatchNormalization_2/bn/gamma
    int v12_shape[4];
    rt_variable_t v13; ///< BatchNormalization_2/bn/mean
    int v13_shape[4];
    rt_variable_t v14; ///< BatchNormalization_2/bn/var
    int v14_shape[4];
    rt_variable_t v15; ///< Convolution_5/conv/W
    int v15_shape[4];
    rt_variable_t v16; ///< Convolution_5/conv/b
    int v16_shape[1];
    rt_variable_t v17; ///< BatchNormalization_4/bn/beta
    int v17_shape[4];
    rt_variable_t v18; ///< BatchNormalization_4/bn/gamma
    int v18_shape[4];
    rt_variable_t v19; ///< BatchNormalization_4/bn/mean
    int v19_shape[4];
    rt_variable_t v20; ///< BatchNormalization_4/bn/var
    int v20_shape[4];
    rt_variable_t v21; ///< Affine/affine/W
    int v21_shape[2];
    rt_variable_t v22; ///< Affine/affine/b
    int v22_shape[1];
    rt_variable_t v23; ///< Affine_3/affine/W
    int v23_shape[2];
    rt_variable_t v24; ///< Affine_3/affine/b
    int v24_shape[1];
    rt_variable_t v25; ///< Convolution
    int v25_shape[4];
    rt_variable_t v26; ///< Convolution_2
    int v26_shape[4];
    rt_variable_t v27; ///< BatchNormalization
    int v27_shape[4];
    rt_variable_t v28; ///< MaxPooling
    int v28_shape[4];
    rt_variable_t v29; ///< ReLU
    int v29_shape[4];
    rt_variable_t v30; ///< Convolution_3
    int v30_shape[4];
    rt_variable_t v31; ///< BatchNormalization_2
    int v31_shape[4];
    rt_variable_t v32; ///< MaxPooling_2
    int v32_shape[4];
    rt_variable_t v33; ///< ReLU_2
    int v33_shape[4];
    rt_variable_t v34; ///< Convolution_5
    int v34_shape[4];
    rt_variable_t v35; ///< BatchNormalization_4
    int v35_shape[4];
    rt_variable_t v36; ///< MaxPooling_4
    int v36_shape[4];
    rt_variable_t v37; ///< ReLU_4
    int v37_shape[4];
    rt_variable_t v38; ///< Affine
    int v38_shape[2];
    rt_variable_t v39; ///< ReLU_10
    int v39_shape[2];
    rt_variable_t v40; ///< Affine_3
    int v40_shape[2];

    // Functions
    rt_function_t f0; ///< Convolution
    rt_variable_t* f0_inputs[3];
    rt_variable_t* f0_outputs[1];
    convolution_local_context_t *f0_local_context;
    int f0_local_context_shape_pad[2];
    int f0_local_context_shape_stride[2];
    int f0_local_context_shape_dilation[2];
    rt_function_t f1; ///< Convolution
    rt_variable_t* f1_inputs[3];
    rt_variable_t* f1_outputs[1];
    convolution_local_context_t *f1_local_context;
    int f1_local_context_shape_pad[2];
    int f1_local_context_shape_stride[2];
    int f1_local_context_shape_dilation[2];
    rt_function_t f2; ///< BatchNormalization
    rt_variable_t* f2_inputs[5];
    rt_variable_t* f2_outputs[1];
    batch_normalization_local_context_t *f2_local_context;
    int f2_local_context_shape_axes[1];
    rt_function_t f3; ///< MaxPooling
    rt_variable_t* f3_inputs[1];
    rt_variable_t* f3_outputs[1];
    max_pooling_local_context_t *f3_local_context;
    int f3_local_context_shape_kernel[2];
    int f3_local_context_shape_stride[2];
    int f3_local_context_shape_pad[2];
    rt_function_t f4; ///< ReLU
    rt_variable_t* f4_inputs[1];
    rt_variable_t* f4_outputs[1];
    relu_local_context_t *f4_local_context;
    rt_function_t f5; ///< Convolution
    rt_variable_t* f5_inputs[3];
    rt_variable_t* f5_outputs[1];
    convolution_local_context_t *f5_local_context;
    int f5_local_context_shape_pad[2];
    int f5_local_context_shape_stride[2];
    int f5_local_context_shape_dilation[2];
    rt_function_t f6; ///< BatchNormalization
    rt_variable_t* f6_inputs[5];
    rt_variable_t* f6_outputs[1];
    batch_normalization_local_context_t *f6_local_context;
    int f6_local_context_shape_axes[1];
    rt_function_t f7; ///< MaxPooling
    rt_variable_t* f7_inputs[1];
    rt_variable_t* f7_outputs[1];
    max_pooling_local_context_t *f7_local_context;
    int f7_local_context_shape_kernel[2];
    int f7_local_context_shape_stride[2];
    int f7_local_context_shape_pad[2];
    rt_function_t f8; ///< ReLU
    rt_variable_t* f8_inputs[1];
    rt_variable_t* f8_outputs[1];
    relu_local_context_t *f8_local_context;
    rt_function_t f9; ///< Convolution
    rt_variable_t* f9_inputs[3];
    rt_variable_t* f9_outputs[1];
    convolution_local_context_t *f9_local_context;
    int f9_local_context_shape_pad[2];
    int f9_local_context_shape_stride[2];
    int f9_local_context_shape_dilation[2];
    rt_function_t f10; ///< BatchNormalization
    rt_variable_t* f10_inputs[5];
    rt_variable_t* f10_outputs[1];
    batch_normalization_local_context_t *f10_local_context;
    int f10_local_context_shape_axes[1];
    rt_function_t f11; ///< MaxPooling
    rt_variable_t* f11_inputs[1];
    rt_variable_t* f11_outputs[1];
    max_pooling_local_context_t *f11_local_context;
    int f11_local_context_shape_kernel[2];
    int f11_local_context_shape_stride[2];
    int f11_local_context_shape_pad[2];
    rt_function_t f12; ///< ReLU
    rt_variable_t* f12_inputs[1];
    rt_variable_t* f12_outputs[1];
    relu_local_context_t *f12_local_context;
    rt_function_t f13; ///< Affine
    rt_variable_t* f13_inputs[3];
    rt_variable_t* f13_outputs[1];
    affine_local_context_t *f13_local_context;
    rt_function_t f14; ///< ReLU
    rt_variable_t* f14_inputs[1];
    rt_variable_t* f14_outputs[1];
    relu_local_context_t *f14_local_context;
    rt_function_t f15; ///< Affine
    rt_variable_t* f15_inputs[3];
    rt_variable_t* f15_outputs[1];
    affine_local_context_t *f15_local_context;
} nnablart_mainruntime_local_context_t;

int actual_buf_sizes[2] = {
    76800,
    76800,
};

void *(*rt_variable_malloc_func)(size_t size) = malloc;
void (*rt_variable_free_func)(void *ptr) = free;

void *(*rt_malloc_func)(size_t size) = malloc;
void (*rt_free_func)(void *ptr) = free;


void* nnablart_mainruntime_allocate_context(void** params)
{
    nnablart_mainruntime_local_context_t* c = malloc(sizeof(nnablart_mainruntime_local_context_t));
    // Variable buffer
    for (int i = 0; i < 2; i++) {
        c->buffer_pool[i] = malloc(sizeof(float) * actual_buf_sizes[i]);
        memset(c->buffer_pool[i], 0, sizeof(float) * actual_buf_sizes[i]);
    }
    if(params) {
        c->variable_buffers_allocate_type[1] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[0] = *params++;
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[1] = *params++;
        c->variable_buffers_allocate_type[3] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[2] = *params++;
        c->variable_buffers_allocate_type[4] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[3] = *params++;
        c->variable_buffers_allocate_type[5] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[4] = *params++;
        c->variable_buffers_allocate_type[6] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[5] = *params++;
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[6] = *params++;
        c->variable_buffers_allocate_type[8] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[7] = *params++;
        c->variable_buffers_allocate_type[9] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[8] = *params++;
        c->variable_buffers_allocate_type[10] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[9] = *params++;
        c->variable_buffers_allocate_type[11] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[10] = *params++;
        c->variable_buffers_allocate_type[12] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[11] = *params++;
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[12] = *params++;
        c->variable_buffers_allocate_type[14] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[13] = *params++;
        c->variable_buffers_allocate_type[15] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[14] = *params++;
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[15] = *params++;
        c->variable_buffers_allocate_type[17] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[16] = *params++;
        c->variable_buffers_allocate_type[18] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[17] = *params++;
        c->variable_buffers_allocate_type[19] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[18] = *params++;
        c->variable_buffers_allocate_type[20] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[19] = *params++;
        c->variable_buffers_allocate_type[21] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[20] = *params++;
        c->variable_buffers_allocate_type[22] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[21] = *params++;
        c->variable_buffers_allocate_type[23] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[22] = *params++;
        c->variable_buffers_allocate_type[24] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[23] = *params++;
    } else {
        c->variable_buffers_allocate_type[1] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[0] = *params++;
        c->param_pool[0] = malloc(sizeof(float) * 1);
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[1] = *params++;
        c->param_pool[1] = malloc(sizeof(float) * 1);
        c->variable_buffers_allocate_type[3] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[2] = *params++;
        c->param_pool[2] = malloc(sizeof(float) * 400);
        c->variable_buffers_allocate_type[4] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[3] = *params++;
        c->param_pool[3] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[5] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[4] = *params++;
        c->param_pool[4] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[6] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[5] = *params++;
        c->param_pool[5] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[6] = *params++;
        c->param_pool[6] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[8] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[7] = *params++;
        c->param_pool[7] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[9] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[8] = *params++;
        c->param_pool[8] = malloc(sizeof(float) * 12800);
        c->variable_buffers_allocate_type[10] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[9] = *params++;
        c->param_pool[9] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[11] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[10] = *params++;
        c->param_pool[10] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[12] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[11] = *params++;
        c->param_pool[11] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[12] = *params++;
        c->param_pool[12] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[14] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[13] = *params++;
        c->param_pool[13] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[15] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[14] = *params++;
        c->param_pool[14] = malloc(sizeof(float) * 9216);
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[15] = *params++;
        c->param_pool[15] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[17] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[16] = *params++;
        c->param_pool[16] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[18] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[17] = *params++;
        c->param_pool[17] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[19] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[18] = *params++;
        c->param_pool[18] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[20] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[19] = *params++;
        c->param_pool[19] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[21] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[20] = *params++;
        c->param_pool[20] = malloc(sizeof(float) * 2048);
        c->variable_buffers_allocate_type[22] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[21] = *params++;
        c->param_pool[21] = malloc(sizeof(float) * 32);
        c->variable_buffers_allocate_type[23] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[22] = *params++;
        c->param_pool[22] = malloc(sizeof(float) * 160);
        c->variable_buffers_allocate_type[24] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[23] = *params++;
        c->param_pool[23] = malloc(sizeof(float) * 5);
    }

    // Variables
    // Input
    (c->v0).type = NN_DATA_TYPE_FLOAT;
    (c->v0).shape.size = 4;
    c->v0_shape[0] = 1;
    c->v0_shape[1] = 1;
    c->v0_shape[2] = 60;
    c->v0_shape[3] = 80;
    (c->v0).shape.data = c->v0_shape;
    (c->v0).data = c->buffer_pool[0];
    // Convolution/conv/W
    (c->v1).type = NN_DATA_TYPE_FLOAT;
    (c->v1).shape.size = 4;
    c->v1_shape[0] = 1;
    c->v1_shape[1] = 1;
    c->v1_shape[2] = 1;
    c->v1_shape[3] = 1;
    (c->v1).shape.data = c->v1_shape;
    (c->v1).data = c->param_pool[0];
    // Convolution/conv/b
    (c->v2).type = NN_DATA_TYPE_FLOAT;
    (c->v2).shape.size = 1;
    c->v2_shape[0] = 1;
    (c->v2).shape.data = c->v2_shape;
    (c->v2).data = c->param_pool[1];
    // Convolution_2/conv/W
    (c->v3).type = NN_DATA_TYPE_FLOAT;
    (c->v3).shape.size = 4;
    c->v3_shape[0] = 16;
    c->v3_shape[1] = 1;
    c->v3_shape[2] = 5;
    c->v3_shape[3] = 5;
    (c->v3).shape.data = c->v3_shape;
    (c->v3).data = c->param_pool[2];
    // Convolution_2/conv/b
    (c->v4).type = NN_DATA_TYPE_FLOAT;
    (c->v4).shape.size = 1;
    c->v4_shape[0] = 16;
    (c->v4).shape.data = c->v4_shape;
    (c->v4).data = c->param_pool[3];
    // BatchNormalization/bn/beta
    (c->v5).type = NN_DATA_TYPE_FLOAT;
    (c->v5).shape.size = 4;
    c->v5_shape[0] = 1;
    c->v5_shape[1] = 16;
    c->v5_shape[2] = 1;
    c->v5_shape[3] = 1;
    (c->v5).shape.data = c->v5_shape;
    (c->v5).data = c->param_pool[4];
    // BatchNormalization/bn/gamma
    (c->v6).type = NN_DATA_TYPE_FLOAT;
    (c->v6).shape.size = 4;
    c->v6_shape[0] = 1;
    c->v6_shape[1] = 16;
    c->v6_shape[2] = 1;
    c->v6_shape[3] = 1;
    (c->v6).shape.data = c->v6_shape;
    (c->v6).data = c->param_pool[5];
    // BatchNormalization/bn/mean
    (c->v7).type = NN_DATA_TYPE_FLOAT;
    (c->v7).shape.size = 4;
    c->v7_shape[0] = 1;
    c->v7_shape[1] = 16;
    c->v7_shape[2] = 1;
    c->v7_shape[3] = 1;
    (c->v7).shape.data = c->v7_shape;
    (c->v7).data = c->param_pool[6];
    // BatchNormalization/bn/var
    (c->v8).type = NN_DATA_TYPE_FLOAT;
    (c->v8).shape.size = 4;
    c->v8_shape[0] = 1;
    c->v8_shape[1] = 16;
    c->v8_shape[2] = 1;
    c->v8_shape[3] = 1;
    (c->v8).shape.data = c->v8_shape;
    (c->v8).data = c->param_pool[7];
    // Convolution_3/conv/W
    (c->v9).type = NN_DATA_TYPE_FLOAT;
    (c->v9).shape.size = 4;
    c->v9_shape[0] = 32;
    c->v9_shape[1] = 16;
    c->v9_shape[2] = 5;
    c->v9_shape[3] = 5;
    (c->v9).shape.data = c->v9_shape;
    (c->v9).data = c->param_pool[8];
    // Convolution_3/conv/b
    (c->v10).type = NN_DATA_TYPE_FLOAT;
    (c->v10).shape.size = 1;
    c->v10_shape[0] = 32;
    (c->v10).shape.data = c->v10_shape;
    (c->v10).data = c->param_pool[9];
    // BatchNormalization_2/bn/beta
    (c->v11).type = NN_DATA_TYPE_FLOAT;
    (c->v11).shape.size = 4;
    c->v11_shape[0] = 1;
    c->v11_shape[1] = 32;
    c->v11_shape[2] = 1;
    c->v11_shape[3] = 1;
    (c->v11).shape.data = c->v11_shape;
    (c->v11).data = c->param_pool[10];
    // BatchNormalization_2/bn/gamma
    (c->v12).type = NN_DATA_TYPE_FLOAT;
    (c->v12).shape.size = 4;
    c->v12_shape[0] = 1;
    c->v12_shape[1] = 32;
    c->v12_shape[2] = 1;
    c->v12_shape[3] = 1;
    (c->v12).shape.data = c->v12_shape;
    (c->v12).data = c->param_pool[11];
    // BatchNormalization_2/bn/mean
    (c->v13).type = NN_DATA_TYPE_FLOAT;
    (c->v13).shape.size = 4;
    c->v13_shape[0] = 1;
    c->v13_shape[1] = 32;
    c->v13_shape[2] = 1;
    c->v13_shape[3] = 1;
    (c->v13).shape.data = c->v13_shape;
    (c->v13).data = c->param_pool[12];
    // BatchNormalization_2/bn/var
    (c->v14).type = NN_DATA_TYPE_FLOAT;
    (c->v14).shape.size = 4;
    c->v14_shape[0] = 1;
    c->v14_shape[1] = 32;
    c->v14_shape[2] = 1;
    c->v14_shape[3] = 1;
    (c->v14).shape.data = c->v14_shape;
    (c->v14).data = c->param_pool[13];
    // Convolution_5/conv/W
    (c->v15).type = NN_DATA_TYPE_FLOAT;
    (c->v15).shape.size = 4;
    c->v15_shape[0] = 32;
    c->v15_shape[1] = 32;
    c->v15_shape[2] = 3;
    c->v15_shape[3] = 3;
    (c->v15).shape.data = c->v15_shape;
    (c->v15).data = c->param_pool[14];
    // Convolution_5/conv/b
    (c->v16).type = NN_DATA_TYPE_FLOAT;
    (c->v16).shape.size = 1;
    c->v16_shape[0] = 32;
    (c->v16).shape.data = c->v16_shape;
    (c->v16).data = c->param_pool[15];
    // BatchNormalization_4/bn/beta
    (c->v17).type = NN_DATA_TYPE_FLOAT;
    (c->v17).shape.size = 4;
    c->v17_shape[0] = 1;
    c->v17_shape[1] = 32;
    c->v17_shape[2] = 1;
    c->v17_shape[3] = 1;
    (c->v17).shape.data = c->v17_shape;
    (c->v17).data = c->param_pool[16];
    // BatchNormalization_4/bn/gamma
    (c->v18).type = NN_DATA_TYPE_FLOAT;
    (c->v18).shape.size = 4;
    c->v18_shape[0] = 1;
    c->v18_shape[1] = 32;
    c->v18_shape[2] = 1;
    c->v18_shape[3] = 1;
    (c->v18).shape.data = c->v18_shape;
    (c->v18).data = c->param_pool[17];
    // BatchNormalization_4/bn/mean
    (c->v19).type = NN_DATA_TYPE_FLOAT;
    (c->v19).shape.size = 4;
    c->v19_shape[0] = 1;
    c->v19_shape[1] = 32;
    c->v19_shape[2] = 1;
    c->v19_shape[3] = 1;
    (c->v19).shape.data = c->v19_shape;
    (c->v19).data = c->param_pool[18];
    // BatchNormalization_4/bn/var
    (c->v20).type = NN_DATA_TYPE_FLOAT;
    (c->v20).shape.size = 4;
    c->v20_shape[0] = 1;
    c->v20_shape[1] = 32;
    c->v20_shape[2] = 1;
    c->v20_shape[3] = 1;
    (c->v20).shape.data = c->v20_shape;
    (c->v20).data = c->param_pool[19];
    // Affine/affine/W
    (c->v21).type = NN_DATA_TYPE_FLOAT;
    (c->v21).shape.size = 2;
    c->v21_shape[0] = 64;
    c->v21_shape[1] = 32;
    (c->v21).shape.data = c->v21_shape;
    (c->v21).data = c->param_pool[20];
    // Affine/affine/b
    (c->v22).type = NN_DATA_TYPE_FLOAT;
    (c->v22).shape.size = 1;
    c->v22_shape[0] = 32;
    (c->v22).shape.data = c->v22_shape;
    (c->v22).data = c->param_pool[21];
    // Affine_3/affine/W
    (c->v23).type = NN_DATA_TYPE_FLOAT;
    (c->v23).shape.size = 2;
    c->v23_shape[0] = 32;
    c->v23_shape[1] = 5;
    (c->v23).shape.data = c->v23_shape;
    (c->v23).data = c->param_pool[22];
    // Affine_3/affine/b
    (c->v24).type = NN_DATA_TYPE_FLOAT;
    (c->v24).shape.size = 1;
    c->v24_shape[0] = 5;
    (c->v24).shape.data = c->v24_shape;
    (c->v24).data = c->param_pool[23];
    // Convolution
    (c->v25).type = NN_DATA_TYPE_FLOAT;
    (c->v25).shape.size = 4;
    c->v25_shape[0] = 1;
    c->v25_shape[1] = 1;
    c->v25_shape[2] = 60;
    c->v25_shape[3] = 80;
    (c->v25).shape.data = c->v25_shape;
    (c->v25).data = c->buffer_pool[1];
    // Convolution_2
    (c->v26).type = NN_DATA_TYPE_FLOAT;
    (c->v26).shape.size = 4;
    c->v26_shape[0] = 1;
    c->v26_shape[1] = 16;
    c->v26_shape[2] = 60;
    c->v26_shape[3] = 80;
    (c->v26).shape.data = c->v26_shape;
    (c->v26).data = c->buffer_pool[0];
    // BatchNormalization
    (c->v27).type = NN_DATA_TYPE_FLOAT;
    (c->v27).shape.size = 4;
    c->v27_shape[0] = 1;
    c->v27_shape[1] = 16;
    c->v27_shape[2] = 60;
    c->v27_shape[3] = 80;
    (c->v27).shape.data = c->v27_shape;
    (c->v27).data = c->buffer_pool[1];
    // MaxPooling
    (c->v28).type = NN_DATA_TYPE_FLOAT;
    (c->v28).shape.size = 4;
    c->v28_shape[0] = 1;
    c->v28_shape[1] = 16;
    c->v28_shape[2] = 15;
    c->v28_shape[3] = 20;
    (c->v28).shape.data = c->v28_shape;
    (c->v28).data = c->buffer_pool[0];
    // ReLU
    (c->v29).type = NN_DATA_TYPE_FLOAT;
    (c->v29).shape.size = 4;
    c->v29_shape[0] = 1;
    c->v29_shape[1] = 16;
    c->v29_shape[2] = 15;
    c->v29_shape[3] = 20;
    (c->v29).shape.data = c->v29_shape;
    (c->v29).data = c->buffer_pool[1];
    // Convolution_3
    (c->v30).type = NN_DATA_TYPE_FLOAT;
    (c->v30).shape.size = 4;
    c->v30_shape[0] = 1;
    c->v30_shape[1] = 32;
    c->v30_shape[2] = 15;
    c->v30_shape[3] = 20;
    (c->v30).shape.data = c->v30_shape;
    (c->v30).data = c->buffer_pool[0];
    // BatchNormalization_2
    (c->v31).type = NN_DATA_TYPE_FLOAT;
    (c->v31).shape.size = 4;
    c->v31_shape[0] = 1;
    c->v31_shape[1] = 32;
    c->v31_shape[2] = 15;
    c->v31_shape[3] = 20;
    (c->v31).shape.data = c->v31_shape;
    (c->v31).data = c->buffer_pool[1];
    // MaxPooling_2
    (c->v32).type = NN_DATA_TYPE_FLOAT;
    (c->v32).shape.size = 4;
    c->v32_shape[0] = 1;
    c->v32_shape[1] = 32;
    c->v32_shape[2] = 3;
    c->v32_shape[3] = 5;
    (c->v32).shape.data = c->v32_shape;
    (c->v32).data = c->buffer_pool[0];
    // ReLU_2
    (c->v33).type = NN_DATA_TYPE_FLOAT;
    (c->v33).shape.size = 4;
    c->v33_shape[0] = 1;
    c->v33_shape[1] = 32;
    c->v33_shape[2] = 3;
    c->v33_shape[3] = 5;
    (c->v33).shape.data = c->v33_shape;
    (c->v33).data = c->buffer_pool[1];
    // Convolution_5
    (c->v34).type = NN_DATA_TYPE_FLOAT;
    (c->v34).shape.size = 4;
    c->v34_shape[0] = 1;
    c->v34_shape[1] = 32;
    c->v34_shape[2] = 3;
    c->v34_shape[3] = 5;
    (c->v34).shape.data = c->v34_shape;
    (c->v34).data = c->buffer_pool[0];
    // BatchNormalization_4
    (c->v35).type = NN_DATA_TYPE_FLOAT;
    (c->v35).shape.size = 4;
    c->v35_shape[0] = 1;
    c->v35_shape[1] = 32;
    c->v35_shape[2] = 3;
    c->v35_shape[3] = 5;
    (c->v35).shape.data = c->v35_shape;
    (c->v35).data = c->buffer_pool[1];
    // MaxPooling_4
    (c->v36).type = NN_DATA_TYPE_FLOAT;
    (c->v36).shape.size = 4;
    c->v36_shape[0] = 1;
    c->v36_shape[1] = 32;
    c->v36_shape[2] = 1;
    c->v36_shape[3] = 2;
    (c->v36).shape.data = c->v36_shape;
    (c->v36).data = c->buffer_pool[0];
    // ReLU_4
    (c->v37).type = NN_DATA_TYPE_FLOAT;
    (c->v37).shape.size = 4;
    c->v37_shape[0] = 1;
    c->v37_shape[1] = 32;
    c->v37_shape[2] = 1;
    c->v37_shape[3] = 2;
    (c->v37).shape.data = c->v37_shape;
    (c->v37).data = c->buffer_pool[1];
    // Affine
    (c->v38).type = NN_DATA_TYPE_FLOAT;
    (c->v38).shape.size = 2;
    c->v38_shape[0] = 1;
    c->v38_shape[1] = 32;
    (c->v38).shape.data = c->v38_shape;
    (c->v38).data = c->buffer_pool[0];
    // ReLU_10
    (c->v39).type = NN_DATA_TYPE_FLOAT;
    (c->v39).shape.size = 2;
    c->v39_shape[0] = 1;
    c->v39_shape[1] = 32;
    (c->v39).shape.data = c->v39_shape;
    (c->v39).data = c->buffer_pool[1];
    // Affine_3
    (c->v40).type = NN_DATA_TYPE_FLOAT;
    (c->v40).shape.size = 2;
    c->v40_shape[0] = 1;
    c->v40_shape[1] = 5;
    (c->v40).shape.data = c->v40_shape;
    (c->v40).data = c->buffer_pool[0];

    // Functions
    // Convolution
    c->f0_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f0).num_of_inputs = 3;
    (c->f0_inputs)[0] = &(c->v0);
    (c->f0_inputs)[1] = &(c->v1);
    (c->f0_inputs)[2] = &(c->v2);
    (c->f0).inputs = c->f0_inputs;
    (c->f0).num_of_outputs = 1;
    (c->f0_outputs)[0] = &(c->v25);
    (c->f0).outputs = c->f0_outputs;
    (c->f0).local_context = c->f0_local_context;
    (c->f0_local_context)->base_axis = 1;
    rt_list_t arg_f0_pad;
    arg_f0_pad.size = 2;
    arg_f0_pad.data = c->f0_local_context_shape_pad;
    arg_f0_pad.data[0] = 0;
    arg_f0_pad.data[1] = 0;
    (c->f0_local_context)->pad = arg_f0_pad;
    rt_list_t arg_f0_stride;
    arg_f0_stride.size = 2;
    arg_f0_stride.data = c->f0_local_context_shape_stride;
    arg_f0_stride.data[0] = 1;
    arg_f0_stride.data[1] = 1;
    (c->f0_local_context)->stride = arg_f0_stride;
    rt_list_t arg_f0_dilation;
    arg_f0_dilation.size = 2;
    arg_f0_dilation.data = c->f0_local_context_shape_dilation;
    arg_f0_dilation.data[0] = 1;
    arg_f0_dilation.data[1] = 1;
    (c->f0_local_context)->dilation = arg_f0_dilation;
    (c->f0_local_context)->group = 1;
    (c->f0_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f0));
    // Convolution
    c->f1_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f1).num_of_inputs = 3;
    (c->f1_inputs)[0] = &(c->v25);
    (c->f1_inputs)[1] = &(c->v3);
    (c->f1_inputs)[2] = &(c->v4);
    (c->f1).inputs = c->f1_inputs;
    (c->f1).num_of_outputs = 1;
    (c->f1_outputs)[0] = &(c->v26);
    (c->f1).outputs = c->f1_outputs;
    (c->f1).local_context = c->f1_local_context;
    (c->f1_local_context)->base_axis = 1;
    rt_list_t arg_f1_pad;
    arg_f1_pad.size = 2;
    arg_f1_pad.data = c->f1_local_context_shape_pad;
    arg_f1_pad.data[0] = 2;
    arg_f1_pad.data[1] = 2;
    (c->f1_local_context)->pad = arg_f1_pad;
    rt_list_t arg_f1_stride;
    arg_f1_stride.size = 2;
    arg_f1_stride.data = c->f1_local_context_shape_stride;
    arg_f1_stride.data[0] = 1;
    arg_f1_stride.data[1] = 1;
    (c->f1_local_context)->stride = arg_f1_stride;
    rt_list_t arg_f1_dilation;
    arg_f1_dilation.size = 2;
    arg_f1_dilation.data = c->f1_local_context_shape_dilation;
    arg_f1_dilation.data[0] = 1;
    arg_f1_dilation.data[1] = 1;
    (c->f1_local_context)->dilation = arg_f1_dilation;
    (c->f1_local_context)->group = 1;
    (c->f1_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f1));
    // BatchNormalization
    c->f2_local_context = malloc(sizeof(batch_normalization_local_context_t));
    (c->f2).num_of_inputs = 5;
    (c->f2_inputs)[0] = &(c->v26);
    (c->f2_inputs)[1] = &(c->v5);
    (c->f2_inputs)[2] = &(c->v6);
    (c->f2_inputs)[3] = &(c->v7);
    (c->f2_inputs)[4] = &(c->v8);
    (c->f2).inputs = c->f2_inputs;
    (c->f2).num_of_outputs = 1;
    (c->f2_outputs)[0] = &(c->v27);
    (c->f2).outputs = c->f2_outputs;
    (c->f2).local_context = c->f2_local_context;
    rt_list_t arg_f2_axes;
    arg_f2_axes.size = 1;
    arg_f2_axes.data = c->f2_local_context_shape_axes;
    arg_f2_axes.data[0] = 1;
    (c->f2_local_context)->axes = arg_f2_axes;
    (c->f2_local_context)->decay_rate = 0.8999999761581421;
    (c->f2_local_context)->eps = 9.999999747378752e-05;
    (c->f2_local_context)->batch_stat = 0;
    (c->f2_local_context)->no_scale = 0;
    (c->f2_local_context)->no_bias = 0;
    allocate_batch_normalization_local_context(&(c->f2));
    // MaxPooling
    c->f3_local_context = malloc(sizeof(max_pooling_local_context_t));
    (c->f3).num_of_inputs = 1;
    (c->f3_inputs)[0] = &(c->v27);
    (c->f3).inputs = c->f3_inputs;
    (c->f3).num_of_outputs = 1;
    (c->f3_outputs)[0] = &(c->v28);
    (c->f3).outputs = c->f3_outputs;
    (c->f3).local_context = c->f3_local_context;
    rt_list_t arg_f3_kernel;
    arg_f3_kernel.size = 2;
    arg_f3_kernel.data = c->f3_local_context_shape_kernel;
    arg_f3_kernel.data[0] = 4;
    arg_f3_kernel.data[1] = 4;
    (c->f3_local_context)->kernel = arg_f3_kernel;
    rt_list_t arg_f3_stride;
    arg_f3_stride.size = 2;
    arg_f3_stride.data = c->f3_local_context_shape_stride;
    arg_f3_stride.data[0] = 4;
    arg_f3_stride.data[1] = 4;
    (c->f3_local_context)->stride = arg_f3_stride;
    (c->f3_local_context)->ignore_border = 1;
    rt_list_t arg_f3_pad;
    arg_f3_pad.size = 2;
    arg_f3_pad.data = c->f3_local_context_shape_pad;
    arg_f3_pad.data[0] = 0;
    arg_f3_pad.data[1] = 0;
    (c->f3_local_context)->pad = arg_f3_pad;
    (c->f3_local_context)->channel_last = 0;
    allocate_max_pooling_local_context(&(c->f3));
    // ReLU
    c->f4_local_context = malloc(sizeof(relu_local_context_t));
    (c->f4).num_of_inputs = 1;
    (c->f4_inputs)[0] = &(c->v28);
    (c->f4).inputs = c->f4_inputs;
    (c->f4).num_of_outputs = 1;
    (c->f4_outputs)[0] = &(c->v29);
    (c->f4).outputs = c->f4_outputs;
    (c->f4).local_context = c->f4_local_context;
    (c->f4_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f4));
    // Convolution
    c->f5_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f5).num_of_inputs = 3;
    (c->f5_inputs)[0] = &(c->v29);
    (c->f5_inputs)[1] = &(c->v9);
    (c->f5_inputs)[2] = &(c->v10);
    (c->f5).inputs = c->f5_inputs;
    (c->f5).num_of_outputs = 1;
    (c->f5_outputs)[0] = &(c->v30);
    (c->f5).outputs = c->f5_outputs;
    (c->f5).local_context = c->f5_local_context;
    (c->f5_local_context)->base_axis = 1;
    rt_list_t arg_f5_pad;
    arg_f5_pad.size = 2;
    arg_f5_pad.data = c->f5_local_context_shape_pad;
    arg_f5_pad.data[0] = 2;
    arg_f5_pad.data[1] = 2;
    (c->f5_local_context)->pad = arg_f5_pad;
    rt_list_t arg_f5_stride;
    arg_f5_stride.size = 2;
    arg_f5_stride.data = c->f5_local_context_shape_stride;
    arg_f5_stride.data[0] = 1;
    arg_f5_stride.data[1] = 1;
    (c->f5_local_context)->stride = arg_f5_stride;
    rt_list_t arg_f5_dilation;
    arg_f5_dilation.size = 2;
    arg_f5_dilation.data = c->f5_local_context_shape_dilation;
    arg_f5_dilation.data[0] = 1;
    arg_f5_dilation.data[1] = 1;
    (c->f5_local_context)->dilation = arg_f5_dilation;
    (c->f5_local_context)->group = 1;
    (c->f5_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f5));
    // BatchNormalization
    c->f6_local_context = malloc(sizeof(batch_normalization_local_context_t));
    (c->f6).num_of_inputs = 5;
    (c->f6_inputs)[0] = &(c->v30);
    (c->f6_inputs)[1] = &(c->v11);
    (c->f6_inputs)[2] = &(c->v12);
    (c->f6_inputs)[3] = &(c->v13);
    (c->f6_inputs)[4] = &(c->v14);
    (c->f6).inputs = c->f6_inputs;
    (c->f6).num_of_outputs = 1;
    (c->f6_outputs)[0] = &(c->v31);
    (c->f6).outputs = c->f6_outputs;
    (c->f6).local_context = c->f6_local_context;
    rt_list_t arg_f6_axes;
    arg_f6_axes.size = 1;
    arg_f6_axes.data = c->f6_local_context_shape_axes;
    arg_f6_axes.data[0] = 1;
    (c->f6_local_context)->axes = arg_f6_axes;
    (c->f6_local_context)->decay_rate = 0.8999999761581421;
    (c->f6_local_context)->eps = 9.999999747378752e-05;
    (c->f6_local_context)->batch_stat = 0;
    (c->f6_local_context)->no_scale = 0;
    (c->f6_local_context)->no_bias = 0;
    allocate_batch_normalization_local_context(&(c->f6));
    // MaxPooling
    c->f7_local_context = malloc(sizeof(max_pooling_local_context_t));
    (c->f7).num_of_inputs = 1;
    (c->f7_inputs)[0] = &(c->v31);
    (c->f7).inputs = c->f7_inputs;
    (c->f7).num_of_outputs = 1;
    (c->f7_outputs)[0] = &(c->v32);
    (c->f7).outputs = c->f7_outputs;
    (c->f7).local_context = c->f7_local_context;
    rt_list_t arg_f7_kernel;
    arg_f7_kernel.size = 2;
    arg_f7_kernel.data = c->f7_local_context_shape_kernel;
    arg_f7_kernel.data[0] = 4;
    arg_f7_kernel.data[1] = 4;
    (c->f7_local_context)->kernel = arg_f7_kernel;
    rt_list_t arg_f7_stride;
    arg_f7_stride.size = 2;
    arg_f7_stride.data = c->f7_local_context_shape_stride;
    arg_f7_stride.data[0] = 4;
    arg_f7_stride.data[1] = 4;
    (c->f7_local_context)->stride = arg_f7_stride;
    (c->f7_local_context)->ignore_border = 1;
    rt_list_t arg_f7_pad;
    arg_f7_pad.size = 2;
    arg_f7_pad.data = c->f7_local_context_shape_pad;
    arg_f7_pad.data[0] = 0;
    arg_f7_pad.data[1] = 0;
    (c->f7_local_context)->pad = arg_f7_pad;
    (c->f7_local_context)->channel_last = 0;
    allocate_max_pooling_local_context(&(c->f7));
    // ReLU
    c->f8_local_context = malloc(sizeof(relu_local_context_t));
    (c->f8).num_of_inputs = 1;
    (c->f8_inputs)[0] = &(c->v32);
    (c->f8).inputs = c->f8_inputs;
    (c->f8).num_of_outputs = 1;
    (c->f8_outputs)[0] = &(c->v33);
    (c->f8).outputs = c->f8_outputs;
    (c->f8).local_context = c->f8_local_context;
    (c->f8_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f8));
    // Convolution
    c->f9_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f9).num_of_inputs = 3;
    (c->f9_inputs)[0] = &(c->v33);
    (c->f9_inputs)[1] = &(c->v15);
    (c->f9_inputs)[2] = &(c->v16);
    (c->f9).inputs = c->f9_inputs;
    (c->f9).num_of_outputs = 1;
    (c->f9_outputs)[0] = &(c->v34);
    (c->f9).outputs = c->f9_outputs;
    (c->f9).local_context = c->f9_local_context;
    (c->f9_local_context)->base_axis = 1;
    rt_list_t arg_f9_pad;
    arg_f9_pad.size = 2;
    arg_f9_pad.data = c->f9_local_context_shape_pad;
    arg_f9_pad.data[0] = 1;
    arg_f9_pad.data[1] = 1;
    (c->f9_local_context)->pad = arg_f9_pad;
    rt_list_t arg_f9_stride;
    arg_f9_stride.size = 2;
    arg_f9_stride.data = c->f9_local_context_shape_stride;
    arg_f9_stride.data[0] = 1;
    arg_f9_stride.data[1] = 1;
    (c->f9_local_context)->stride = arg_f9_stride;
    rt_list_t arg_f9_dilation;
    arg_f9_dilation.size = 2;
    arg_f9_dilation.data = c->f9_local_context_shape_dilation;
    arg_f9_dilation.data[0] = 1;
    arg_f9_dilation.data[1] = 1;
    (c->f9_local_context)->dilation = arg_f9_dilation;
    (c->f9_local_context)->group = 1;
    (c->f9_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f9));
    // BatchNormalization
    c->f10_local_context = malloc(sizeof(batch_normalization_local_context_t));
    (c->f10).num_of_inputs = 5;
    (c->f10_inputs)[0] = &(c->v34);
    (c->f10_inputs)[1] = &(c->v17);
    (c->f10_inputs)[2] = &(c->v18);
    (c->f10_inputs)[3] = &(c->v19);
    (c->f10_inputs)[4] = &(c->v20);
    (c->f10).inputs = c->f10_inputs;
    (c->f10).num_of_outputs = 1;
    (c->f10_outputs)[0] = &(c->v35);
    (c->f10).outputs = c->f10_outputs;
    (c->f10).local_context = c->f10_local_context;
    rt_list_t arg_f10_axes;
    arg_f10_axes.size = 1;
    arg_f10_axes.data = c->f10_local_context_shape_axes;
    arg_f10_axes.data[0] = 1;
    (c->f10_local_context)->axes = arg_f10_axes;
    (c->f10_local_context)->decay_rate = 0.8999999761581421;
    (c->f10_local_context)->eps = 9.999999747378752e-05;
    (c->f10_local_context)->batch_stat = 0;
    (c->f10_local_context)->no_scale = 0;
    (c->f10_local_context)->no_bias = 0;
    allocate_batch_normalization_local_context(&(c->f10));
    // MaxPooling
    c->f11_local_context = malloc(sizeof(max_pooling_local_context_t));
    (c->f11).num_of_inputs = 1;
    (c->f11_inputs)[0] = &(c->v35);
    (c->f11).inputs = c->f11_inputs;
    (c->f11).num_of_outputs = 1;
    (c->f11_outputs)[0] = &(c->v36);
    (c->f11).outputs = c->f11_outputs;
    (c->f11).local_context = c->f11_local_context;
    rt_list_t arg_f11_kernel;
    arg_f11_kernel.size = 2;
    arg_f11_kernel.data = c->f11_local_context_shape_kernel;
    arg_f11_kernel.data[0] = 2;
    arg_f11_kernel.data[1] = 2;
    (c->f11_local_context)->kernel = arg_f11_kernel;
    rt_list_t arg_f11_stride;
    arg_f11_stride.size = 2;
    arg_f11_stride.data = c->f11_local_context_shape_stride;
    arg_f11_stride.data[0] = 2;
    arg_f11_stride.data[1] = 2;
    (c->f11_local_context)->stride = arg_f11_stride;
    (c->f11_local_context)->ignore_border = 1;
    rt_list_t arg_f11_pad;
    arg_f11_pad.size = 2;
    arg_f11_pad.data = c->f11_local_context_shape_pad;
    arg_f11_pad.data[0] = 0;
    arg_f11_pad.data[1] = 0;
    (c->f11_local_context)->pad = arg_f11_pad;
    (c->f11_local_context)->channel_last = 0;
    allocate_max_pooling_local_context(&(c->f11));
    // ReLU
    c->f12_local_context = malloc(sizeof(relu_local_context_t));
    (c->f12).num_of_inputs = 1;
    (c->f12_inputs)[0] = &(c->v36);
    (c->f12).inputs = c->f12_inputs;
    (c->f12).num_of_outputs = 1;
    (c->f12_outputs)[0] = &(c->v37);
    (c->f12).outputs = c->f12_outputs;
    (c->f12).local_context = c->f12_local_context;
    (c->f12_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f12));
    // Affine
    c->f13_local_context = malloc(sizeof(affine_local_context_t));
    (c->f13).num_of_inputs = 3;
    (c->f13_inputs)[0] = &(c->v37);
    (c->f13_inputs)[1] = &(c->v21);
    (c->f13_inputs)[2] = &(c->v22);
    (c->f13).inputs = c->f13_inputs;
    (c->f13).num_of_outputs = 1;
    (c->f13_outputs)[0] = &(c->v38);
    (c->f13).outputs = c->f13_outputs;
    (c->f13).local_context = c->f13_local_context;
    (c->f13_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f13));
    // ReLU
    c->f14_local_context = malloc(sizeof(relu_local_context_t));
    (c->f14).num_of_inputs = 1;
    (c->f14_inputs)[0] = &(c->v38);
    (c->f14).inputs = c->f14_inputs;
    (c->f14).num_of_outputs = 1;
    (c->f14_outputs)[0] = &(c->v39);
    (c->f14).outputs = c->f14_outputs;
    (c->f14).local_context = c->f14_local_context;
    (c->f14_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f14));
    // Affine
    c->f15_local_context = malloc(sizeof(affine_local_context_t));
    (c->f15).num_of_inputs = 3;
    (c->f15_inputs)[0] = &(c->v39);
    (c->f15_inputs)[1] = &(c->v23);
    (c->f15_inputs)[2] = &(c->v24);
    (c->f15).inputs = c->f15_inputs;
    (c->f15).num_of_outputs = 1;
    (c->f15_outputs)[0] = &(c->v40);
    (c->f15).outputs = c->f15_outputs;
    (c->f15).local_context = c->f15_local_context;
    (c->f15_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f15));
    return (void*)c;
}

int nnablart_mainruntime_free_context(void* context)
{
    nnablart_mainruntime_local_context_t* c = (nnablart_mainruntime_local_context_t*)context;

    for (int i = 0; i < 2; i++) {
        free(c->buffer_pool[i]);
    }
    if(c->variable_buffers_allocate_type[1] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[0]);
    }
    if(c->variable_buffers_allocate_type[2] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[1]);
    }
    if(c->variable_buffers_allocate_type[3] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[2]);
    }
    if(c->variable_buffers_allocate_type[4] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[3]);
    }
    if(c->variable_buffers_allocate_type[5] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[4]);
    }
    if(c->variable_buffers_allocate_type[6] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[5]);
    }
    if(c->variable_buffers_allocate_type[7] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[6]);
    }
    if(c->variable_buffers_allocate_type[8] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[7]);
    }
    if(c->variable_buffers_allocate_type[9] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[8]);
    }
    if(c->variable_buffers_allocate_type[10] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[9]);
    }
    if(c->variable_buffers_allocate_type[11] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[10]);
    }
    if(c->variable_buffers_allocate_type[12] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[11]);
    }
    if(c->variable_buffers_allocate_type[13] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[12]);
    }
    if(c->variable_buffers_allocate_type[14] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[13]);
    }
    if(c->variable_buffers_allocate_type[15] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[14]);
    }
    if(c->variable_buffers_allocate_type[16] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[15]);
    }
    if(c->variable_buffers_allocate_type[17] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[16]);
    }
    if(c->variable_buffers_allocate_type[18] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[17]);
    }
    if(c->variable_buffers_allocate_type[19] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[18]);
    }
    if(c->variable_buffers_allocate_type[20] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[19]);
    }
    if(c->variable_buffers_allocate_type[21] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[20]);
    }
    if(c->variable_buffers_allocate_type[22] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[21]);
    }
    if(c->variable_buffers_allocate_type[23] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[22]);
    }
    if(c->variable_buffers_allocate_type[24] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[23]);
    }
    free_convolution_local_context(&(c->f0));
    if (c->f0.local_context != 0) {
        rt_free_func(c->f0.local_context);
        c->f0.local_context = 0;
    }
    free_convolution_local_context(&(c->f1));
    if (c->f1.local_context != 0) {
        rt_free_func(c->f1.local_context);
        c->f1.local_context = 0;
    }
    free_batch_normalization_local_context(&(c->f2));
    if (c->f2.local_context != 0) {
        rt_free_func(c->f2.local_context);
        c->f2.local_context = 0;
    }
    free_max_pooling_local_context(&(c->f3));
    if (c->f3.local_context != 0) {
        rt_free_func(c->f3.local_context);
        c->f3.local_context = 0;
    }
    free_relu_local_context(&(c->f4));
    if (c->f4.local_context != 0) {
        rt_free_func(c->f4.local_context);
        c->f4.local_context = 0;
    }
    free_convolution_local_context(&(c->f5));
    if (c->f5.local_context != 0) {
        rt_free_func(c->f5.local_context);
        c->f5.local_context = 0;
    }
    free_batch_normalization_local_context(&(c->f6));
    if (c->f6.local_context != 0) {
        rt_free_func(c->f6.local_context);
        c->f6.local_context = 0;
    }
    free_max_pooling_local_context(&(c->f7));
    if (c->f7.local_context != 0) {
        rt_free_func(c->f7.local_context);
        c->f7.local_context = 0;
    }
    free_relu_local_context(&(c->f8));
    if (c->f8.local_context != 0) {
        rt_free_func(c->f8.local_context);
        c->f8.local_context = 0;
    }
    free_convolution_local_context(&(c->f9));
    if (c->f9.local_context != 0) {
        rt_free_func(c->f9.local_context);
        c->f9.local_context = 0;
    }
    free_batch_normalization_local_context(&(c->f10));
    if (c->f10.local_context != 0) {
        rt_free_func(c->f10.local_context);
        c->f10.local_context = 0;
    }
    free_max_pooling_local_context(&(c->f11));
    if (c->f11.local_context != 0) {
        rt_free_func(c->f11.local_context);
        c->f11.local_context = 0;
    }
    free_relu_local_context(&(c->f12));
    if (c->f12.local_context != 0) {
        rt_free_func(c->f12.local_context);
        c->f12.local_context = 0;
    }
    free_affine_local_context(&(c->f13));
    if (c->f13.local_context != 0) {
        rt_free_func(c->f13.local_context);
        c->f13.local_context = 0;
    }
    free_relu_local_context(&(c->f14));
    if (c->f14.local_context != 0) {
        rt_free_func(c->f14.local_context);
        c->f14.local_context = 0;
    }
    free_affine_local_context(&(c->f15));
    if (c->f15.local_context != 0) {
        rt_free_func(c->f15.local_context);
        c->f15.local_context = 0;
    }  
    free(context);
    return NN_ERROR_CODE_NOERROR;
}

float* nnablart_mainruntime_input_buffer(void* context, int index)
{
    nnablart_mainruntime_local_context_t* c = (nnablart_mainruntime_local_context_t*)context;
    switch(index) {
        case 0: return (c->v0).data;
    }
    return 0;
}

float* nnablart_mainruntime_output_buffer(void* context, int index)
{
    nnablart_mainruntime_local_context_t* c = (nnablart_mainruntime_local_context_t*)context;
    switch(index) {
        case 0: return (c->v40).data;
    }

    return 0;
}
float* nnablart_mainruntime_param_buffer(void* context, int index)
{
    nnablart_mainruntime_local_context_t* c = (nnablart_mainruntime_local_context_t*)context;
    switch(index) {
        case 0: return (c->v21).data;
        case 1: return (c->v22).data;
        case 2: return (c->v23).data;
        case 3: return (c->v24).data;
        case 4: return (c->v5).data;
        case 5: return (c->v6).data;
        case 6: return (c->v7).data;
        case 7: return (c->v8).data;
        case 8: return (c->v11).data;
        case 9: return (c->v12).data;
        case 10: return (c->v13).data;
        case 11: return (c->v14).data;
        case 12: return (c->v17).data;
        case 13: return (c->v18).data;
        case 14: return (c->v19).data;
        case 15: return (c->v20).data;
        case 16: return (c->v1).data;
        case 17: return (c->v2).data;
        case 18: return (c->v3).data;
        case 19: return (c->v4).data;
        case 20: return (c->v9).data;
        case 21: return (c->v10).data;
        case 22: return (c->v15).data;
        case 23: return (c->v16).data;
    }
    return 0;
}
int nnablart_mainruntime_inference(void* context)
{
    nnablart_mainruntime_local_context_t* c = (nnablart_mainruntime_local_context_t*)context;
    exec_convolution(&(c->f0));
    exec_convolution(&(c->f1));
    exec_batch_normalization(&(c->f2));
    exec_max_pooling(&(c->f3));
    exec_relu(&(c->f4));
    exec_convolution(&(c->f5));
    exec_batch_normalization(&(c->f6));
    exec_max_pooling(&(c->f7));
    exec_relu(&(c->f8));
    exec_convolution(&(c->f9));
    exec_batch_normalization(&(c->f10));
    exec_max_pooling(&(c->f11));
    exec_relu(&(c->f12));
    exec_affine(&(c->f13));
    exec_relu(&(c->f14));
    exec_affine(&(c->f15));
    return NN_ERROR_CODE_NOERROR;
}
